spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project?serverTimezone=Asia/Seoul
    username: azure
    password: azure1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  thymeleaf:
    cache: false
# thymeleaf 파일 수정하고 저장한 후 브라우저에서 변경된 결과 확인하기 위한 설정 /// 개발할때는 false로두고 나중에 true로 변경